apiVersion: apps/v1
kind: Deployment
metadata:
  name: cliente
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cliente
  template:
    metadata:
      labels:
        app: cliente
    spec:
      containers:
        - name: cliente
          image: mauron/cliente:v1
          ports:
            - containerPort: 8080
          envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: cliente
spec:
  selector:
    app: cliente
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8080
  type: LoadBalancer
