apiVersion: apps/v1
kind: Deployment
metadata:
  name: factura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: factura
  template:
    metadata:
      labels:
        app: factura
    spec:
      containers:
        - name: factura
          image: mauron/factura:v6
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 11
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: factura
spec:
  selector:
    app: factura
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: factura
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: factura
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80