apiVersion: apps/v1
kind: Deployment
metadata:
  name: factura
spec:
  replicas: 5
  selector:
    matchLabels:
      app: factura
  template:
    metadata:
      labels:
        app: factura
    spec:
      containers:
        - name: factura
          image: mauron/factura:v6
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: jdbc:postgresql://postgres:5432/postgres
            - name: DATABASE_USERNAME
              value: postgres
            - name: DATABASE_PASSWORD
              value: "123456"
            - name: JAVA_OPTS
              value: -Xms256m -Xmx512m
            - name: LOGSTASH_SERVER
              value: logstash:5000
---
apiVersion: v1
kind: Service
metadata:
  name: factura
spec:
  selector:
    app: factura
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8080
  type: LoadBalancer
