name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Listar directorios
      run: ls -al
        
    - name: Build with Maven
      run: |
          cd factura 
          mvn clean package -DskipTests
          ls -al target

    - name: Build docker images
      run: |
        cd factura
        docker build -t ms-factura:${{ github.run_number }} .

    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
